spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=liquibase_db;encrypt=false
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true